import { supabase } from '@/lib/supabase';
import type { UserProfile } from '@/types';

export class AuthError extends Error { code?: string; constructor(message: string, code?: string) { super(message); this.name = 'AuthError'; this.code = code; } }
function mapProfile(profile: Record<string, unknown>): UserProfile { return { id: String(profile.id), firstName: String(profile.first_name ?? ''), lastName: String(profile.last_name ?? ''), email: String(profile.email ?? ''), phone: String(profile.phone ?? ''), role: profile.role === 'admin' ? 'admin' : 'customer', createdAt: String(profile.created_at ?? '') }; }
function translateAuthError(message: string): string { if (/invalid login credentials/i.test(message)) return 'Email ou mot de passe incorrect.'; if (/user already registered/i.test(message)) return 'Un compte existe déjà avec cet email.'; if (/email not confirmed/i.test(message)) return 'Merci de confirmer votre email avant de vous connecter.'; return message; }
async function fetchProfile(userId: string): Promise<UserProfile> { const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).single(); if (error) throw new AuthError(translateAuthError(error.message)); return mapProfile(data); }
export async function getCurrentProfile(userId: string): Promise<UserProfile> { return fetchProfile(userId); }
export type SignUpResult = { status: 'confirmed' | 'needs_email_confirmation'; profile: UserProfile };
export async function signUp(input: { firstName: string; lastName: string; email: string; phone: string; password: string }): Promise<SignUpResult> { const { data, error } = await supabase.auth.signUp({ email: input.email, password: input.password, options: { data: { first_name: input.firstName, last_name: input.lastName, phone: input.phone } } }); if (error || !data.user) throw new AuthError(translateAuthError(error?.message ?? 'Impossible de créer le compte.'), error?.code); if (!data.session) return { status: 'needs_email_confirmation', profile: { id: data.user.id, firstName: input.firstName, lastName: input.lastName, email: input.email, phone: input.phone, role: 'customer', createdAt: data.user.created_at } }; return { status: 'confirmed', profile: await fetchProfile(data.user.id) }; }
export async function signIn(email: string, password: string): Promise<UserProfile> { const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error || !data.user) throw new AuthError(translateAuthError(error?.message ?? 'Connexion impossible.'), error?.code); return fetchProfile(data.user.id); }
export async function requestPasswordReset(email: string, redirectTo?: string): Promise<void> { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: redirectTo ?? `${window.location.origin}/reset-password` }); if (error) throw new AuthError(translateAuthError(error.message)); }
export async function updateProfile(userId: string, updates: Partial<Pick<UserProfile, 'firstName' | 'lastName' | 'phone'>>): Promise<UserProfile> { const payload = { ...(updates.firstName === undefined ? {} : { first_name: updates.firstName }), ...(updates.lastName === undefined ? {} : { last_name: updates.lastName }), ...(updates.phone === undefined ? {} : { phone: updates.phone }) }; const { data, error } = await supabase.from('profiles').update(payload).eq('id', userId).select('*').single(); if (error) throw new AuthError(translateAuthError(error.message)); return mapProfile(data); }
export async function updatePassword(newPassword: string): Promise<void> { const { error } = await supabase.auth.updateUser({ password: newPassword }); if (error) throw new AuthError(translateAuthError(error.message)); }
export async function signOut(): Promise<void> { const { error } = await supabase.auth.signOut(); if (error) throw new AuthError(translateAuthError(error.message)); }
